### ISSUE TITLE
Phase error when assembling with omc

### ISSUE THREAD

**Issue by cstrotm** [pkali/Chip-8#1]
I'm trying to assemble the CHIP-8 interpreter with omc (compiled under Linux from the Github sources). I found that "omc" treats all filenames as uppercase, which works on case-insenitive filesystems (such as Windows), but not on Unix/Linux file-systems. However I could work around by renaming all source files to uppercase.

Then, "omc" bails out with a "Phase error" on label "fr55"

```
 OMC - Our 5oft MaCro assembler for 6502, ver. 1.2, (c) 1993 by Our 5oft.
   source  :chip8vA.s65
destination:chip8vA.s65


                   Page 1

 Phase 1
 Phase 2
fr55
 -ERROR! chip8vA.s65 line 1479: Phase error

```

I'm now stuck as I can't see what is causing the phase error. Maybe it's an issue with this version of "omc" and the CHIP-8 source.

**Comment by pkali** [comment]
thank you so much for this report! 
I've already started converting the code to mads, unfortunately, it turned out to be more complicated than expected, primarily because of mac65 I/O macros used. 
There might be a quick solution - running windows omc65 executable with wine. It used to work. I should have one somewhere.

Regarding this particular 'phase error' - it is caused by something above the error message, we never went beyond rather simplistic mac65 error reporting, and mads is so much better that it does not make sense to develop this historic piece of code.
It does look like there is a problem with unixy version.

**Comment by cstrotm** [comment]
Hi Pawel, 

thanks for the quick response. Where can I find a Windows executable of "omc65" (I don't have a Windows system to compile one)?

Also, can you tell me about the License/Copying rules/restrictions of your CHIP-8 interpreter. Is it "open source" (GPL, BSD, MIT ...)  or "public domain" (CC0)?

For now the files on the ATR work fine, but I would like to be able to tweak the code if needed :)

**Comment by pkali** [comment]
I've found the old win32 exe and pushed it here: https://github.com/pkali/omc65/blob/master/omc.exe
also updated the license
haven't checked yet if it compiles, but it, theoretically, should work :)

**Comment by pkali** [comment]
FYI - it worked :)
looks like linux version is somewhat unhealthy
